name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug - List repository contents
        run: |
          echo "Current directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Looking for bot.py:"
          find . -name bot.py
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/botia:latest
          platforms: linux/amd64

      - name: Verify image
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/botia:latest
          echo "Checking container contents:"
          docker run --rm ${{ vars.DOCKERHUB_USERNAME }}/botia:latest ls -la /app