# .github/workflows/docker-publish.yml

name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check Docker Hub Username
      run: echo "Using Docker Hub username: $username"

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/botia:latest
        provenance: false
        platforms: linux/amd64
        outputs: type=docker,dest=/tmp/myimage.tar
        
    - name: Verify image
      run: |
        docker load < /tmp/myimage.tar
        docker image ls    
